cors:
  allowable: "http://localhost:5173"
spring:
  mail:
    host: smtp.qq.com
    username: 568541648@qq.com
    password: nykrgvozkppmbbfa
  rabbitmq:
#    addresses: localhost
    username: root
    password: root
    addresses: 192.168.241.128
    virtual-host: /test
  security:
    user:
      password: 123456
    jwt:
      key: djt
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3307/campus_forum?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  data:
    redis:
      host: localhost
limit:
  time: 60
