#开发环境
cors:
  origin: '*'
#  "http://localhost:5173"
  credentials: false
  methods: '*'
limit:
#  邮箱限制时间，单位秒和ip的请求每分钟限制上限。
  time: 1
  ipRequestLimitNumber : 30
minio:
  address: "http://8.137.49.63:9000/"
  login:
    key: "minio"
    password: "password"
weather :
#  和风天气的 key，
  api: https://geoapi.qweather.com/v2/city/lookup?location=
  key: d2cc04b4f410455b9b0149fdbddebf20
spring:
  mail:
    host: smtp.qq.com
    username: 568541648@qq.com
    password: oeaiayikgqxebbie
  rabbitmq:
    addresses: localhost
    username: root
    password: root
#    addresses: 192.168.241.128
    virtual-host: /test
  security:
    user:
      password: 123456
    jwt:
      key: djt
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3307/campus_forum?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  data:
    redis:
      host: localhost
  #      文件上传相关
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
